Add A Better I18n Support
McJty/TheOneProbe pull request #262
Opened 2018-08-02 16:44 UTC by TartaricAcid

2018-08-10 01:26 UTC, mcBegins2Snow commented
@TartaricAcid I found a typo in zh_cn.lang:
`Line 5:item.theoneprobe.probe_goggles.name=检测器(视频)`
The right name is "检测器（饰品）"

2018-08-29 00:42 UTC, Snownee commented on src/main/java/mcjty/theoneprobe/apiimpl/providers/DefaultProbeInfoProvider.java
> +                    .text(I18n.format("gui.theoneprobe.default_provider.lever.state", LABEL, INFO, (powered ? "On" : "Off")));
I18n for "On" & "Off"?

2018-08-29 00:44 UTC, Snownee commented on src/main/java/mcjty/theoneprobe/apiimpl/providers/DefaultProbeInfoProvider.java
> +                        .text(I18n.format("gui.theoneprobe.default_provider.brewing.fuel", LABEL, INFO, fuel));
Suggestion: do not put formatting texts into language file. It is fixed

2018-08-29 00:56 UTC, Snownee commented on src/main/java/mcjty/theoneprobe/apiimpl/providers/HarvestInfoTools.java
> +                    I18n.format("gui.theoneprobe.harvest_info_tools.harvest_name:" + harvestName.toLowerCase())));
I18n for tool classes?

2019-02-25 21:50 UTC, liach commented
Hmm, anything blocking this? This looks like a nice pr.

2019-02-26 03:49 UTC, 3TUSK requested changes
Some of the `I18n.format` usage may cause dedicate server loading classes that are only available on client side, so thus further testing are needed to ensure no regression are arisen.

2019-02-26 03:49 UTC, 3TUSK commented on src/main/java/mcjty/theoneprobe/apiimpl/providers/DefaultProbeInfoEntityProvider.java
> +                int age = ((EntityAgeable) entity).getGrowingAge();
Formatting

2019-02-26 03:49 UTC, 3TUSK commented on src/main/java/mcjty/theoneprobe/apiimpl/providers/DefaultProbeInfoEntityProvider.java
> +import net.minecraft.entity.*;
Guess there shouldn't be star import for consistency...

2019-02-26 03:49 UTC, 3TUSK commented on src/main/java/mcjty/theoneprobe/gui/GuiConfig.java
> -        addButton(x+10, y, 30, 14, "--", () -> { Config.setScale(1.2f);}); x += 36;
Unnecessary formatting changes?

2019-02-26 04:03 UTC, closed without merging

2020-03-15 01:39 UTC, lihsai0 commented
Anyone take over i18n support?
I want to fix the issue @3TUSK mentioned.
However, set up project error for getting `Tesla-1.12.2/1.0.63/Tesla-1.12.2-1.0.63.pom` 404.